table Medidas
	lineageTag: 8cfa95f3-8166-4d6b-8b55-b99bfce878fa

	measure Medida = 1
		formatString: 0
		lineageTag: b6375a36-f2d1-4262-9286-10b8645ffb95

	partition Medidas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WSlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Colunas Removidas" = Table.RemoveColumns(Source,{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

